#!/bin/bash

function assert_success() {
    "${@}"
    local status=${?}
    if [ ${status} -ne 0 ]; then
        echo "### Error ${status} at: ${BASH_LINENO[*]} ###"
        exit ${status}
    fi
}

version="2.249.1"

assert_success docker build -t jenkins:$version ./
assert_success docker tag jenkins:$version insanusmokrassar/jenkins:$version
assert_success docker tag jenkins:$version insanusmokrassar/jenkins:latest
assert_success docker push insanusmokrassar/jenkins
